apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "postgres.name" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "postgres.name" . }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "postgres.fullname" . }}-secret
      #     volumeMounts:
      #       - name: postgres-storage
      #         mountPath: /var/lib/postgresql/data
      #         subPath: postgres
      # volumes:
      #   - name: postgres-storage
      #     persistentVolumeClaim:
      #       claimName: {{ include "postgres.fullname" . }}-pvc
