image:
  repository: postgres
  tag: "13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

postgresUser: postgres
postgresPassword: postgres
postgresDb: notesdb

persistence:
  enabled: false
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

resources: {}
